name: Build Kivy App with Buildozer

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          python3-pip \
          python3-setuptools \
          openjdk-8-jdk \
          git \
          unzip
        pip install --upgrade pip
        pip install buildozer kivy

    - name: Set up Android SDK/NDK
      run: |
        # Create necessary directories
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools

        # Download and unzip the SDK command-line tools
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o cmdline-tools.zip
        unzip cmdline-tools.zip -d ./

        # Fix directory structure
        mv cmdline-tools/* .
        rmdir cmdline-tools

        # Accept the licenses and install necessary components
        yes | ./bin/sdkmanager --licenses
        ./bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;29.0.2" "platforms;android-29" "aidl"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug
      env:
        HOME: $HOME

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./bin/*.apk


