name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-11-jdk curl \
            libffi-dev libssl-dev \
            python3-dev python3-pip \
            lib32z1 lib32ncurses6 libbz2-1.0 libstdc++6

      - name: Install Android SDK and Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools

          # Download Android command-line tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

          # Set SDK root
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          # Accept licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install platform tools, build-tools, and platforms
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;33.0.0" \
            "build-tools;33.0.2" \
            "build-tools;34.0.0" \
            "platforms;android-33"

      - name: Debug AIDL Availability
        run: ls $HOME/android-sdk/build-tools/33.0.0

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export PATH=$ANDROIDSDK/platform-tools:$ANDROIDSDK/build-tools/33.0.0:$PATH
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
