on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Android SDK and Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools

          # Download Android command-line tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

          # Set SDK root
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          # Accept licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install platform tools, build-tools, and platforms
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;33.0.0" \
            "platforms;android-33"

          # Ensure build-tools/33.0.0/aidl exists
          if [ ! -f "$ANDROID_SDK_ROOT/build-tools/33.0.0/aidl" ]; then
            echo "Error: aidl is missing in build-tools"
            exit 1
          fi

      - name: Build APK with Hardcoded Paths
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export PATH=$ANDROIDSDK/platform-tools:$ANDROIDSDK/build-tools/33.0.0:$PATH
          buildozer -v android debug



