name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-11-jdk curl \
            libffi-dev libssl-dev \
            python3-dev python3-pip lib32z1 lib32ncurses6 libbz2-1.0 libstdc++6
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK and Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools

          # Download and install command-line tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

          # Install stable versions of SDK components
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;33.0.0" \
            "platforms;android-33"

      - name: Accept Licenses Manually
        run: |
          mkdir -p $HOME/android-sdk/licenses
          echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/android-sdk/licenses/android-sdk-license
          echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/android-sdk/licenses/android-sdk-preview-license

      - name: Debug Android SDK
        run: |
          ls $HOME/android-sdk/build-tools
          ls $HOME/android-sdk/build-tools/33.0.0

      - name: Build with Buildozer
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.0:$PATH
          buildozer -v android debug

      - name: Debug Build Logs
        run: cat .buildozer/android/platform/build/build.log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: .buildozer/android/platform/build/dists/*/bin/*.apk


